### ISSUE TITLE
$count Query

### ISSUE THREAD

**Issue by shashankp** [hassanhabib/ODataWithoutEF#1]
Included Count QuerySetting, but, $count query isn't adding count of objects in the result JSON

`
app.UseMvc(builder =>
            {
                ...
                builder.Expand().Select().Count().OrderBy().Filter();
            });
`

Other settings such as $orderby, $filter are working as expected.
Does $count need any additional step?

**Comment by ronaldoperes** [comment]
> Included Count QuerySetting, but, $count query isn't adding count of objects in the result JSON
> 
> `app.UseMvc(builder => { ... builder.Expand().Select().Count().OrderBy().Filter(); });`
> 
> Other settings such as $orderby, $filter are working as expected.
> Does $count need any additional step?

Hi,

According to Hassan, 

You’re going to need to use the EDM route to get count, check it out here in this blog post: https://devblogs.microsoft.com/odata/simplifying-edm-with-odata/

Regards

**Comment by shashankp** [comment]
thanks @ronaldoperes
